[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-env"
version = "0.36.0"

[lib]
name = "spk_env"
path = "src/lib.rs"

[dependencies]
relative-path = "1.3"
spk-ident-ops = { path = "../spk-ident-ops" }