[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = { workspace = true }
name = "spfs"
version = "0.34.6"

[features]
default = []

# If enabled, will create the "local" repository in a subdirectory
# of the standard storage root, named "ci/pipeline_${CI_PIPELINE_ID}".
gitlab-ci-local-repo-isolation = []
sentry = ["dep:sentry"]
server = [
    "hyper/server",
    "tokio-util/codec",
    "tokio-util/io",
    "tokio-util/io-util",
]
"protobuf-src" = ["dep:protobuf-src"]

[dependencies]
async-trait = "0.1.52"
async-recursion = "1.0"
async-stream = "0.3"
caps = "0.5.3"
chrono = { workspace = true }
close-err = "1.0"
cnproc = { git = "https://github.com/rydrman/cnproc-rs", branch = "act-like-iterator" }
colored = "2.0"
config = "0.13.1"
data-encoding = "2.3"
expanduser = "1.2"
faccess = "0.2.3"
futures = "0.3.9"
gitignore = "1.0"
glob = "0.3.0"
hyper = { version = "0.14.16", features = ["client"] }
indicatif = "0.16.2"
itertools = "0.10.3"
lazy_static = "1.4"
libc = "0.2.80"
nix = "0.24.1"
nonempty = "0.8.1"
once_cell = "1.8"
procfs = { workspace = true }
prost = "0.11"
rand = "0.8.5"
relative-path = "1.3"
ring = "0.16.15"
semver = "1.0"
sentry = { workspace = true, optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
serde_qs = "0.10.1"
spfs-encoding = {path = "../spfs-encoding"}
strum_macros = "0.24.2"
tar = "0.4.30"
tempfile = { workspace = true }
tokio = { version = "1.20", features = [
    "fs",
    "io-util",
    "io-std",
    "rt",
    "rt-multi-thread",
    "macros",
    "sync",
    "process",
    "signal"
] }
tokio-stream = { version = "0.1", features = ["net"] }
tokio-util = { version = "0.7.3", features = ["compat"] }
tonic = "0.8"
tracing = "0.1.22"
url = { version = "2.2", features = ["serde"] }
uuid = { version = "1.1", features = ["v4"] }
walkdir = "2.3"
whoami = "1.2"
thiserror = "1.0"

[build-dependencies]
protobuf-src = { version = "1.0.5", optional = true } # protoc @ 3.19.3
tonic-build = "0.8"

[dev-dependencies]
criterion = { version = "0.3", features = ["async_tokio", "html_reports"] }
rstest = { version = "0.15.0", default_features = false }
serial_test = "0.8.0"
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }

[[bench]]
name = "spfs_bench"
harness = false
