[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spfs-encoding"
version = "0.34.6"

[lib]
name = "spfs_encoding"
path = "src/lib.rs"

[dependencies]
async-stream = "0.3"
async-trait = "0.1.52"
close-err = "1.0"
data-encoding = "2.3"
futures = "0.3.9"
libc = "0.2.80"
rand = "0.8.5"
ring = "0.16.15"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.20", features = [
    "fs",
    "io-util",
    "io-std",
    "rt",
    "rt-multi-thread",
    "macros",
    "sync",
    "process",
    "signal"
] }
tokio-stream = { version = "0.1", features = ["net"] }

[dev-dependencies]
rstest = { version = "0.15.0", default_features = false }