[profile.release]
lto = true
codegen-units = 1

[workspace]
members = [
    "crates/spfs-encoding",
    "crates/spfs",
    "crates/spk-build",
    "crates/spk-cli/*",
    "crates/spfs-cli/*",
    "crates/spk-exec",
    "crates/spk-launcher",
    "crates/spk-schema",
    "crates/spk-solve",
    "crates/spk-solve/crates/*",
    "crates/spk-storage",
    "crates/spk",
]

[workspace.package]
edition = "2021"
version = "0.36.0"

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1"
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.2", features = ["derive", "env"] }
colored = "2.0.0"
procfs = "0.13.2"
rstest = "0.15.0"
sentry = { version = "0.27.0" }
sentry-anyhow = { version = "0.27.0" }
tempfile = "3.3"
tokio = { version = "1.20", features = ["rt"] }
tracing = "0.1.35"