[profile.release]
lto = true
codegen-units = 1

[workspace]
members = [
    "crates/spk",
    "crates/spk-build",
    "crates/spk-build-ops",
    "crates/spk-env",
    "crates/spk-exec",
    "crates/spk-fixtures",
    "crates/spk-format",
    "crates/spk-ident",
    "crates/spk-ident-build",
    "crates/spk-ident-component",
    "crates/spk-ident-ops",
    "crates/spk-launcher",
    "crates/spk-name",
    "crates/spk-option-map",
    "crates/spk-solver",
    "crates/spk-spec",
    "crates/spk-spec-ops",
    "crates/spk-storage",
    "crates/spk-validators",
    "crates/spk-version",
    "crates/spk-version-range",
    "crates/spfs"
]
