[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2018"
name = "spk"
version = "0.32.0"

[lib]
name = "spk"
path = "src/lib.rs"

[[bin]]
name = "spk"
path = "src/cli/bin.rs"

[features]
sentry = ["dep:sentry", "dep:sentry-anyhow", "dep:sentry-tracing"]
fixtures = ["dep:rstest"]
test-macros = []
migration-to-components = []

[dependencies]
anyhow = "1.0.56"
async-recursion = "1.0"
async-stream = "0.3"
async-trait = "0.1"
clap = { version = "3.2", features = ["derive", "env"] }
colored = "2.0.0"
console = "0.15"
data-encoding = "2.3.0"
dyn-clone = "1.0.4"
enum_dispatch = "0.3.8"
futures = "0.3.9"
glob = "0.3.0"
ignore = "0.4.18"
indexmap = "1.7.0"
itertools = "0.9"
lazy_static = "1.4.0"
nom = "7.1"
nom-supreme = "0.8"
once_cell = "1.8.0"
paste = "1.0"
priority-queue = "1.2"
rand = "0.8"
regex = "1.5.4"
relative-path = "1.3.2"
ring = "0.16.15"
rstest = { version = "0.9.0", optional = true }
serde = { version = "1.0.117", features = ["derive"] }
serde_derive = "1.0.118"
serde_json = "1.0.57"
serde_yaml = "0.8.17"
sentry = { version = "0.27.0", optional = true }
sentry-anyhow = { version = "0.27.0", optional = true }
sentry-tracing = { version = "0.27.0", optional = true }
signal-hook = "0.3"
spfs = { git = 'https://github.com/imageworks/spfs', tag = 'v0.34.5' }
sys-info = "0.9.0"
tar = "0.4.30"
tempdir = "0.3.7"
thiserror = "1.0"
tokio = { version = "1.15", features = ["rt"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }
url = "2.2"
whoami = "1.2"

[target.'cfg(target_os = "linux")'.dependencies]
nix = "0.23.1"

[dev-dependencies]
proptest = "1.0.0"
spk = { path = ".", features = ["fixtures", "test-macros"] }

[profile.release]
lto = true
codegen-units = 1

[workspace]
members = ["spk-launcher"]
