[profile.release]
lto = true
codegen-units = 1

[workspace]
members = [
    "crates/spk",
    "crates/spk-build",
    "crates/spk-build-ops",
    "crates/spk-cli-group1",
    "crates/spk-cli-group2",
    "crates/spk-cli-group3",
    "crates/spk-cli-group4",
    "crates/spk-cli-common",
    "crates/spk-cmd-build",
    "crates/spk-cmd-convert",
    "crates/spk-cmd-env",
    "crates/spk-cmd-explain",
    "crates/spk-cmd-install",
    "crates/spk-cmd-make-binary",
    "crates/spk-cmd-make-source",
    "crates/spk-cmd-render",
    "crates/spk-cmd-repo",
    "crates/spk-cmd-test",
    "crates/spk-exec",
    "crates/spk-foundation",
    "crates/spk-ident",
    "crates/spk-launcher",
    "crates/spk-name",
    "crates/spk-solver",
    "crates/spk-solver-graph",
    "crates/spk-solver-package-iterator",
    "crates/spk-solver-solution",
    "crates/spk-solver-validation",
    "crates/spk-spec",
    "crates/spk-storage",
    "crates/spk-validators",
    "crates/spk-version",
    "crates/spfs"
]
