[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-solver"
version = "0.36.0"

[lib]
name = "spk_solver"
path = "src/lib.rs"

[dependencies]
async-recursion = "1.0"
async-stream = "0.3"
async-trait = "0.1"
colored = "2.0"
ctrlc = "3.2"
futures = "0.3.9"
once_cell = "1.8"
priority-queue = "1.2"
serde_json = "1.0"
spfs = { version = '0.34.6', path = "../spfs" }
spk-foundation = { path = "../spk-foundation" }
spk-ident = { path = "../spk-ident" }
spk-name = { path = "../spk-name" }
spk-solver-graph = { path = "../spk-solver-graph" }
spk-solver-package-iterator = { path = "../spk-solver-package-iterator" }
spk-solver-solution = { path = "../spk-solver-solution" }
spk-solver-validation = { path = "../spk-solver-validation" }
spk-spec = { path = "../spk-spec" }
spk-storage = { path = "../spk-storage" }
spk-validators = { path = "../spk-validators" }
thiserror = "1.0"
tokio = { version = "1.20", features = ["rt"] }
tracing = "0.1.35"

[dev-dependencies]
rstest = "0.15.0"