[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-schema-handlebars"
version = "0.36.0"

[features]
migration-to-components = ["spk-schema-foundation/migration-to-components"]

[dependencies]
handlebars = "4.3.4"
serde = "1.0"
serde_json = "1.0"
spk-schema-foundation = { path = "../foundation" }
tracing = "0.1.35"

[dev-dependencies]
rstest = "0.15.0"
