[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = { workspace = true }
name = "spk-solve-validation"
version = { workspace = true }

[dependencies]
colored = "2.0"
enum_dispatch = "0.3.8"
itertools = "0.10"
spk-solve-graph = { path = "../graph" }
spk-solve-solution = { path = "../solution" }
spk-schema = { path = "../../../spk-schema" }
thiserror = "1.0"

[dev-dependencies]
rstest = { workspace = true }
serde_yaml = "0.8.17"
