[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-solver-validation"
version = "0.36.0"

[lib]
name = "spk_solver_validation"
path = "src/lib.rs"

[dependencies]
colored = "2.0"
enum_dispatch = "0.3.8"
itertools = "0.10"
spk-foundation = { path = "../spk-foundation" }
spk-ident = { path = "../spk-ident" }
spk-name = { path = "../spk-name" }
spk-solver-graph = { path = "../spk-solver-graph" }
spk-solver-solution = { path = "../spk-solver-solution" }
spk-spec = { path = "../spk-spec" }
thiserror = "1.0"

[dev-dependencies]
rstest = "0.15.0"
serde_yaml = "0.8.17"