[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-version"
version = "0.36.0"

[lib]
name = "spk_version"
path = "src/lib.rs"

[dependencies]
itertools = "0.10"
nom = "7.1"
nom-supreme = "0.8"
serde = { version = "1.0", features = ["derive"] }
spk-name = { path = "../spk-name" }
thiserror = "1.0"

[dev-dependencies]
rstest = "0.15.0"
spk-fixtures = { path = "../spk-fixtures" }
tracing = "0.1.35"