[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-format"
version = "0.36.0"

[lib]
name = "spk_format"
path = "src/lib.rs"

[dependencies]
spk-name = { path = "../spk-name" }
thiserror = "1.0"