[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-validators"
version = "0.36.0"

[lib]
name = "spk_validators"
path = "src/lib.rs"

[dependencies]
data-encoding = "2.3.0"
ignore = "0.4.18"
indexmap = "1.7.0"
itertools = "0.10"
nom = "7.1"
regex = "1.5.4"
relative-path = "1.3.2"
ring = "0.16.15"
serde = { version = "1.0.117", features = ["derive"] }
serde_derive = "1.0.118"
serde_json = "1.0.57"
serde_yaml = "0.8.17"
spfs = { version = '0.34.6', path = "../spfs" }
spk-env = { path = "../spk-env" }
spk-foundation = { path = "../spk-foundation" }
spk-ident = { path = "../spk-ident" }
spk-ident-ops = { path = "../spk-ident-ops" }
spk-name = { path = "../spk-name" }
spk-version = { path = "../spk-version" }
sys-info = "0.9.0"
tempdir = "0.3.7"
thiserror = "1.0"
tracing = "0.1.35"

[dev-dependencies]
spk-spec = { path = "../spk-spec" }