[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-schema-ident"
version = "0.36.0"

[dependencies]
colored = "2.0"
format_serde_error = { version = "0.3", default_features = false, features = [
    "serde_yaml",
    "colored",
] }
itertools = "0.10"
nom = "7.1"
nom-supreme = "0.8"
relative-path = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.17"
spk-schema-foundation = { path = "../foundation" }
thiserror = "1.0"

[dev-dependencies]
data-encoding = "2.3"
proptest = "1.0.0"
rstest = "0.15.0"
