[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-ident-ops"
version = "0.36.0"

[lib]
name = "spk_ident_ops"
path = "src/lib.rs"

[dependencies]
relative-path = "1.3"
spk-name = { path = "../spk-name" }
spk-version = { path = "../spk-version" }