[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-build"
version = "0.36.0"

[lib]
name = "spk_build"
path = "src/lib.rs"

[dependencies]
relative-path = "1.3"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8.17"
spfs = { version = '0.34.6', path = "../spfs" }
spk-exec = { path = "../spk-exec" }
spk-foundation = { path = "../spk-foundation" }
spk-ident = { path = "../spk-ident" }
spk-ident-component = { path = "../spk-ident-component" }
spk-name = { path = "../spk-name" }
spk-solver = { path = "../spk-solver" }
spk-solver-graph = { path = "../spk-solver-graph" }
spk-solver-solution = { path = "../spk-solver-solution" }
spk-spec = { path = "../spk-spec" }
spk-storage = { path = "../spk-storage" }
spk-version = { path = "../spk-version" }
thiserror = "1.0"
tokio = { version = "1.20", features = ["rt"] }
tracing = "0.1.35"

[dev-dependencies]
rstest = "0.15.0"
serde_yaml = "0.8.17"
tar = "0.4.30"
tempfile = "3.3"