[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-exec"
version = "0.36.0"

[lib]
name = "spk_exec"
path = "src/lib.rs"

[dependencies]
spfs = { version = '0.34.6', path = "../spfs" }
spk-format = { path = "../spk-format" }
spk-foundation = { path = "../spk-foundation" }
spk-ident-component = { path = "../spk-ident-component" }
spk-solver-solution = { path = "../spk-solver-solution" }
spk-spec = { path = '../spk-spec' }
spk-storage = { path = "../spk-storage" }
thiserror = "1.0"
tracing = "0.1.35"