[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-schema-foundation"
version = "0.36.0"

[features]
migration-to-components = []

[dependencies]
colored = "2.0"
data-encoding = "2.3"
enum_dispatch = "0.3.8"
format_serde_error = {version = "0.3", default_features = false, features = ["serde_yaml", "colored"]}
ignore = "0.4.18"
itertools = "0.10"
nom = "7.1"
nom-supreme = "0.8"
once_cell = "1.8"
paste = "1.0"
relative-path = "1.3"
ring = "0.16.15"
rstest = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.17"
spfs = { version = '0.34.6', path = "../../../spfs" }
sys-info = "0.9.0"
tempfile = "3.3"
thiserror = "1.0"
tracing = "0.1.35"
tracing-subscriber = "0.2.16"

[dev-dependencies]
rstest = "0.15.0"
