[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk"
version = "0.36.0"
default-run = "spk"

[[bin]]
name = "spk"
path = "src/cli.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "3.2", features = ["derive", "env"] }
colored = "2.0.0"
spk-cli-group1 = { path = '../spk-cli-group1' }
spk-cli-group2 = { path = '../spk-cli-group2' }
spk-cli-group3 = { path = '../spk-cli-group3' }
spk-cli-group4 = { path = '../spk-cli-group4' }
spk-cli-common = { path = '../spk-cli-common' }
spk-cmd-build = { path = '../spk-cmd-build' }
spk-cmd-convert = { path = '../spk-cmd-convert' }
spk-cmd-env = { path = '../spk-cmd-env' }
spk-cmd-explain = { path = '../spk-cmd-explain' }
spk-cmd-install = { path = '../spk-cmd-install' }
spk-cmd-make-binary = { path = '../spk-cmd-make-binary' }
spk-cmd-make-source = { path = '../spk-cmd-make-source' }
spk-cmd-render = { path = '../spk-cmd-render' }
spk-cmd-repo = { path = '../spk-cmd-repo' }
spk-cmd-test = { path = '../spk-cmd-test' }
spk-foundation = { path = '../spk-foundation' }
tokio = { version = "1.20", features = ["rt"] }
tracing = "0.1.35"