[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-build-ops"
version = "0.36.0"

[lib]
name = "spk_build_ops"
path = "src/lib.rs"

[dependencies]
relative-path = "1.3"
spfs = { version = '0.34.6', path = "../spfs" }
thiserror = "1.0"