[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-option-map"
version = "0.36.0"

[lib]
name = "spk_option_map"
path = "src/lib.rs"

[dependencies]
colored = "2.0"
data-encoding = "2.3"
itertools = "0.10"
ring = "0.16.15"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.17"
spk-format = { path = "../spk-format" }
spk-name = { path = "../spk-name" }
sys-info = "0.9.0"
thiserror = "1.0"
tracing = "0.1.35"

[dev-dependencies]
rstest = "0.15.0"