[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-spec-ops"
version = "0.36.0"

[lib]
name = "spk_spec_ops"
path = "src/lib.rs"

[dependencies]
enum_dispatch = "0.3.8"
ignore = "0.4.18"
serde = { version = "1.0", features = ["derive"] }
spk-ident-ops = { path = "../spk-ident-ops" }
spk-name = { path = "../spk-name" }
spk-version = { path = "../spk-version" }
thiserror = "1.0"

[dev-dependencies]
rstest = "0.15.0"