[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-solver-package-iterator"
version = "0.36.0"

[lib]
name = "spk_solver_package_iterator"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1"
dyn-clone = "1.0"
futures = "0.3.9"
once_cell = "1.8"
spk-ident = { path = "../spk-ident" }
spk-foundation = { path = "../spk-foundation" }
spk-name = { path = "../spk-name" }
spk-solver-solution = { path = "../spk-solver-solution" }
spk-spec = { path = "../spk-spec" }
spk-storage = { path = "../spk-storage" }
spk-validators = { path = "../spk-validators" }
thiserror = "1.0"
tokio = { version = "1.20", features = ["rt"] }
tracing = "0.1.35"

[dev-dependencies]
itertools = "0.10"
rstest = "0.15.0"
spk-solver = { path = "../spk-solver" }