[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-solver-solution"
version = "0.36.0"

[lib]
name = "spk_solver_solution"
path = "src/lib.rs"

[dependencies]
spfs = { version = '0.34.6', path = "../spfs" }
spk-format = { path = "../spk-format" }
spk-ident = { path = "../spk-ident" }
spk-ident-component = { path = "../spk-ident-component" }
spk-name = { path = "../spk-name" }
spk-option-map = { path = "../spk-option-map" }
spk-spec = { path = "../spk-spec" }
spk-spec-ops = { path = '../spk-spec-ops' }
spk-storage = { path = "../spk-storage" }
spk-version = { path = "../spk-version" }
thiserror = "1.0"