[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = "2021"
name = "spk-solver-solution"
version = "0.36.0"

[lib]
name = "spk_solver_solution"
path = "src/lib.rs"

[dependencies]
spfs = { version = '0.34.6', path = "../spfs" }
spk-foundation = { path = "../spk-foundation" }
spk-ident = { path = "../spk-ident" }
spk-name = { path = "../spk-name" }
spk-spec = { path = "../spk-spec" }
spk-storage = { path = "../spk-storage" }
thiserror = "1.0"